controller_list:
  - name: fake_left_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1_left
      - joint2_left
      - joint3_left
      - joint4_left
      - joint5_left
      - joint6_left
  - name: fake_right_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1_right
      - joint2_right
      - joint3_right
      - joint4_right
      - joint5_right
      - joint6_right
  - name: fake_up_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1_up
      - joint2_up
      - joint3_up
      - joint4_up
      - joint5_up
      - joint6_up
initial:  # Define initial robot poses per group
#  - group: left_arm_group
#    pose: home

  []