left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1_left
    - joint2_left
    - joint3_left
    - joint4_left
    - joint5_left
    - joint6_left
  gains:
    joint1_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1_right
    - joint2_right
    - joint3_right
    - joint4_right
    - joint5_right
    - joint6_right
  gains:
    joint1_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
up_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1_up
    - joint2_up
    - joint3_up
    - joint4_up
    - joint5_up
    - joint6_up
  gains:
    joint1_up:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_up:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_up:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_up:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_up:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6_up:
      p: 100
      d: 1
      i: 1
      i_clamp: 1