fullbot_armleft_j2_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1_left
  pid: {p: 1200.0, i: 5.0, d: 10.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2_left
  pid: {p: 1400.0, i: 5.0, d: 10.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: joint3_left
  pid: {p: 1200.0, i: 5.0, d: 5.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint4_left
  pid: {p: 800.5, i: 3.0, d: 5.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint5_left
  pid: {p: 500.0, i: 3.0, d: 1.0}
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: joint6_left
  pid: {p: 500.0, i: 1.0, d: 1.0}
